# Generated by Django 5.1.5 on 2025-02-10 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativa', '0002_ciudad_docente_ciudad_estudiante_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_ciudad', to='educativa.ciudad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_ciudad', to='educativa.ciudad'),
            preserve_default=False,
        ),
    ]
